<!-- BEGIN .post -->
<div class="post">

        <h2 class="article-title"><a href="#">Maecenas lacus nunc rutrum vitae phaaretra imperdiet</a></h2>

        <div class="info">
                <a href="#" class="time">John Smith @ 09.07.2011</a>
                <a href="#" class="section">Section</a>
                <a href="#" class="comment-nr">9 comments</a>
        </div>

        <a href="#"><img src="/uploads/van_morrison_02.jpg" alt="" /></a>
        <p class="caps">Mecenas neque est, feugiat quis porta in, condimentum eget arcu. Fringilla aliquam ultricies pellente sque vel turpis nec leo tincidunt sollicitudin ac non risus. Ves tibu lum ultrices feugiat velit, quis tincidunt velit volutpat nec. Vivamus pharetra fringilla augue, a elementum ante ultrices tincidunt. Ut mi ligula, interdum ut pharetra id, imperdiet.</p>
        <h3>Section title heading</h3>
        <p>Proin egestas iaculis enim, ullamcorper porttitor justo placerat quis. Sed adipiscing ipsum sed leo molestie auctor. Nam ullamcorper porta lorem ut adipiscing.</p>

        <ul>
                <li>Mauris elit erat, laoreet ac posuere eget, blandit at nunc.</li>
                <li>Vestibulum vitae justo nisi, nec pharetra ipsum fusce lobortis.</li>
                <li>Donec ornare dapibus ante ut porttitor nam sit amet senttima.</li>
                <li>Aliquam vestibulum condimentum leo, vel porta sapien.</li>
        </ul>
        <p>In hac habitasse platea dictumst. Nunc ipsum neque, vulputate nec laoreet at, venenatis at est. Donec et mauris quis tellus pharetra tempor nec eget diam. Nulla sapien diam, tincidunt.</p>

        <p>Nunc ipsum neque, vulputate nec laoreet at, venenatis at est. Donec et mauris quis tellus pharetra tempor nec eget diam. Nulla sapien diam, tincidunt. In hac habitasse platea dictumst.</p>

        <p>In hac habitasse platea dictumst. Nunc ipsum neque, vulputate nec laoreet at, venenatis at est. Donec et mauris quis tellus pharetra tempor nec eget diam. Nulla sapien diam, tincidunt.</p>

        <div class="blockquote-wings">
                <blockquote>
                        Nam sed enim ac diam condimentum blandit, nullam mollis justo vitae ligula lobortis.
                </blockquote>
        </div>

        <p>Nunc ipsum neque, vulputate nec laoreet at, venenatis at est. Donec et mauris quis tellus pharetra tempor nec eget diam. Nulla sapien diam, tincidunt.</p>

        <p>Vamus pharetra fringilla augue, a elementum ante ultrices tincidunt. Ut mi ligula, interdum ut pharetra id, imperdiet. Nullam eget arcu at ipsum condimentum cursus. Curabitur nec pharetra est. Nullam pellentesque aliquet malesuada. Cras facilisis volutpat enim in iaculis. Sed nunc arcu, suscipit quis volutpat sed, semper ac libero.</p>

<!-- END .post -->
</div>

<!-- BEGIN .comments -->
<div class="comments">

        <div class="main-title-1">
                <span>4 comments</span>
        </div>

        <ol>

                <li>
                        <!-- BEGIN .comments-item -->
                        <div class="comments-item">
                                <div class="comments-header">
                                        <div class="user"><span>Malesuada</span><a href="#"><img src="images/ico-user-2.png" alt="" /></a></div>
                                        <div class="time">04.20.2011 @ 9:30 PM</div>
                                </div>
                                <p>Etiam eros massa, consequat in ultricies ac, adipiscing vel eros. Nunc ut enim odio. Integer dap ibus lac inia euismod. Nunc lacinia feugiat vulputate.</p>
                                <p class="reply"><a href="#"><b>Reply</b></a></p>
                        <!-- END .comments-item -->
                        </div>
                </li>

                <li>
                        <!-- BEGIN .comments-item -->
                        <div class="comments-item comments-author">
                                <div class="comments-header">
                                        <div class="user"><span>Vestibulum Eleifend</span><a href="#"><img src="images/ico-user-2.png" alt="" /></a></div>
                                        <div class="time">04.20.2011 @ 9:30 PM</div>
                                </div>
                                <p>Vivamus ultricies, tortor eu imperdiet interdum, diam velit blandit lacus, ut aliquam magna dui vitae magna. Praesent quis massa eget velit vehicula suscipit id ut urna. Integer rhoncus sem nec justo laoreet ultrices. Sed egestas accumsan iaculis.</p>
                                <p class="reply"><a href="#"><b>Reply</b></a></p>
                        <!-- END .comments-item -->
                        </div>
                        <ul>
                                <li>
                                        <!-- BEGIN .comments-item -->
                                        <div class="comments-item">
                                                <div class="comments-header">
                                                        <div class="user"><span>Ullamcorper</span><a href="#"><img src="images/ico-user-2.png" alt="" /></a></div>
                                                        <div class="time">04.20.2011 @ 9:30 PM</div>
                                                </div>
                                                <p>Etiam eros massa, consequat in ultricies ac, adipiscing vel eros. Nunc ut enim odio. Integer dap ibus lac inia euismod. Nunc lacinia feugiat vulputate.</p>
                                                <p class="reply"><a href="#"><b>Reply</b></a></p>
                                        <!-- END .comments-item -->
                                        </div>
                                </li>
                        </ul>
                </li>

                <li>
                        <!-- BEGIN .comments-item -->
                        <div class="comments-item">
                                <div class="comments-header">
                                        <div class="user"><span>Pellentesque Viverra</span><a href="#"><img src="images/ico-user-2.png" alt="Malesuada" /></a></div>
                                        <div class="time">04.20.2011 @ 9:30 PM</div>
                                </div>
                                <p>Proin dapibus augue id quam aliquam lacinia. Maecenas vel magna lorem, nec cursus mi. Fusce sagittis consequat ante, in aliquet metus faucibus a. Maecenas ultricies velit nec sapien consectetur suscipit. Curabitur rhoncus hendrerit sapien, sed venenatis libero porttitor vel.</p>
                                <p class="reply"><a href="#"><b>Reply</b></a></p>
                        <!-- END .comments-item -->
                        </div>
                </li>

        </ol>

        <!-- BEGIN .add-comment -->
        <div class="add-comment">
                <form action="">
                        <table>
                                <tr>
                                        <td class="label">Nickname:</td>
                                        <td><p><input type="text" class="input-text-1" /></p></td>
                                </tr>
                                <tr><td class="comment-spacer-1" colspan="2"></td></tr>
                                <tr>
                                        <td class="label">Your comment:</td>
                                        <td>
                                                <textarea class="text-area-1"></textarea>
                                        </td>
                                </tr>
                                <tr><td class="comment-spacer-1" colspan="2"></td></tr>
                                <tr>
                                        <td></td>
                                        <td><p class="show-all"><a href="menu-card.html" class="btn-1 btn-1-color-default"><span>Add your comment</span></a></p></td>
                                </tr>
                        </table>
                </form>
        <!-- END .add-comment -->
        </div>

        <div class="clear"></div>

<!-- END .comments -->
</div>