<!-- BEGIN .post -->
<div class="post">
        <h2 class="article-title"><a href="#">van morrisson</a></h2>

        <a href="#"><img src="/uploads/vanmorrisson.jpg" alt="" width="449" height="400" /></a>
        <p class="caps" id="testCanvas">Mecenas neque est, feugiat quis porta in, condimentum eget arcu. Fringilla aliquam ultricies pellente sque vel turpis nec leo tincidunt sollicitudin ac non risus. Ves tibu lum ultrices feugiat velit, quis tincidunt velit volutpat nec. Vivamus pharetra fringilla augue, a elementum ante ultrices tincidunt. Ut mi ligula, interdum ut pharetra id, imperdiet.</p>
        <h3>Music</h3>

        <div class="gallery-preview-box">
                <!--<a rel="group" href="http://rockstar.orange-themes.com/wp-content/uploads/2011/12/iStock_000019065835Small.jpg" class="fancy"><img src="http://rockstar.orange-themes.com/wp-content/themes/rockstar/images/image-overlay-125x125.png" alt="Maecenas vitae nibh eu lacus porta feugiat et in lectus. Class aptent taciti." width="125" height="135" class="image" style="background: url(http://rockstar.orange-themes.com/wp-content/themes/rockstar/timthumb.php?src=/wp-content/uploads/2011/12/iStock_000019065835Small.jpg&amp;w=125&amp;h=125&amp;zc=1&amp;q=100) 0 0 no-repeat;"></a>-->
                <!--<a class="albumLoad" rel="samplePlaylist" href="javascript:void(0)"><img src="/uploads/127360.jpg" alt="" width="80" height="90" /></a>
                <a class="albumLoad" rel="samplePlaylist2" href="javascript:void(0)"><img src="/uploads/127360.jpg" alt="" width="80" height="90" /></a>
                <a class="albumLoad" rel="samplePlaylist3" href="javascript:void(0)"><img src="/uploads/127360.jpg" alt="" width="80" height="90" /></a>-->
        </div>
        <div id="songListContainer">
            <div id="songDescription"></div>
            <div id="songList"></div>
        </div>

        <div id="player"></div>

        <!--<div class="blockquote-wings">
                <blockquote>
                        Nam sed enim ac diam condimentum blandit, nullam mollis justo vitae ligula lobortis.
                </blockquote>
        </div>

        <p>Nunc ipsum neque, vulputate nec laoreet at, venenatis at est. Donec et mauris quis tellus pharetra tempor nec eget diam. Nulla sapien diam, tincidunt.</p>

        <table class="image-caption align-center">
                <tr>
                        <td>
                                <img src="images/photos/no-image-342x227.jpg" alt="" />
                                <p>Centered picture with caption</p>
                        </td>
                </tr>
        </table>

        <p>Vamus pharetra fringilla augue, a elementum ante ultrices tincidunt. Ut mi ligula, interdum ut pharetra id, imperdiet. Nullam eget arcu at ipsum condimentum cursus. Curabitur nec pharetra est. Nullam pellentesque aliquet malesuada. Cras facilisis volutpat enim in iaculis. Sed nunc arcu, suscipit quis volutpat sed, semper ac libero.</p>-->

<!-- END .post -->
</div>