<!-- BEGIN .homepage-columns -->
<!--<div class="homepage-columns">-->

        <!-- BEGIN .homepage-columns-item -->
        <!--<div class="homepage-columns-item">
                <div class="title">
                        <div style="background: url(images/ico-guitars-1.png) 0 0 no-repeat; padding-left: 68px;"><span>Awesome guitars</span></div>
                </div>
                <div class="text">
                        <p>Quisque eleifend mi at nisl pretium non dignissim felis euismod. Null am sagittis Integertortoret.</p>
                </div>
            </div>-->
        <!-- END .homepage-columns-item -->

        <!-- BEGIN .homepage-columns-item -->
        <!--<div class="homepage-columns-item">
                <div class="title">
                        <div style="background: url(images/ico-love-1.png) 0 0 no-repeat; padding-left: 72px;"><span>Love for music</span></div>
                </div>
                <div class="text">
                        <p>Integer ac dapibus velit. Suspendisse sit amet orci augue, imperdiet blandit enim. Duis nec mi sapien.</p>
                </div>
            </div>-->
        <!-- END .homepage-columns-item -->

        <!-- BEGIN .homepage-columns-item -->
        <!--<div class="homepage-columns-item last">
                <div class="title">
                        <div style="background: url(images/ico-folder-1.png) 0 0 no-repeat; padding-left: 68px;"><span>Music library</span></div>
                </div>
                <div class="text">
                        <p>Nullam diam nisl, condi in eleifend sit amet, interdum vel quam. Curabitur laoreet viverra eleifend.</p>
                </div>
            </div>-->
        <!-- END .homepage-columns-item -->

<!--</div>-->
<!-- END .homepage-columns -->

<!--<div class="main-spacer-1"></div>

<!-- BEGIN .latest-blog -->
<!--<div class="latest-blog">
        <div class="main-title-1">
                <span>Latest from blog</span>
                <a href="#">check out more</a>
        </div>
        <div class="item">
                <a href="#"><img src="images/image-overlay-235x135.png" alt="" width="235" height="150" style="background: url(images/photos/no-image-235x135.jpg) 0 0 no-repeat;" /></a>
                <div class="title">
                        <a href="#">Proin luctus ullamcorper vulputate nunc vitae</a>
                        <p>Quisque eleifend mi at nisl pretium non dign issim felis euismod. Null am sagittis tech</p>
                </div>
                <p><a href="#" class="more-link"><span>Read more</span></a></p>
        </div>
        <div class="item">
                <a href="#"><img src="images/image-overlay-235x135.png" alt="" width="235" height="150" style="background: url(images/photos/no-image-235x135.jpg) 0 0 no-repeat;" /></a>
                <div class="title">
                        <a href="#">Class aptent taciti sociosqu ad litora torquent</a>
                        <p>Proin eleifend urna sed lorem interdum gravida. Proin non mauris in nulla commodo volutpat eget ut mi.</p>
                </div>
                <p><a href="#" class="more-link"><span>Read more</span></a></p>
        </div>
        <div class="item last">
                <a href="#"><img src="images/image-overlay-235x135.png" alt="" width="235" height="150" style="background: url(images/photos/no-image-235x135.jpg) 0 0 no-repeat;" /></a>
                <div class="title">
                        <a href="#">Pellentesque habitant morbi tristique senectus</a>
                        <p>Aenean vitae nisi purus. Nulla facilisi. Donec a nisi enim, quis congue orci. Vivamusnisl sed massa convallis posuere.</p>
                </div>
                <p><a href="#" class="more-link"><span>Read more</span></a></p>
        </div>
    </div>-->
<!-- END .latest-blog -->

<!--<div class="main-spacer-1"></div>-->

<!--<div class="homepage-twitter">
        <div class="main-title-1">
                <span>Our tweets</span>
                <a href="#">follow us</a>
        </div>
        <div class="item">
                <p><b>Twitter Name:</b> <a href="#">@Crasnon</a> sem in felis consequat cursus vitae pla cerat erat. Ut purus ipsum, laoreet at iaculis non, iaculis.</p>
                <div>
                        <span>about 15 hours ago</span>
                        <a href="#">open tweet</a>
                </div>
        </div>
        <div class="item">
                <p><b>Twitter Name:</b> Phasellus id turpis augue. <a href="#">http://bit.ly/basEts^</a> enim vel nibh commodo fermentum. Mauris sapien erat, rutrumte.</p>
                <div>
                        <span>about 20 hours ago</span>
                        <a href="#">open tweet</a>
                </div>
        </div>
        <div class="item last">
                <p><b>Twitter Name:</b> Vestibulum ullamcorper, ante eget rutrum consectetur, ligula lorem ultricies <a href="#">@liguladui</a></p>
                <div>
                        <span>about 2 days ago</span>
                        <a href="#">open tweet</a>
                </div>
        </div>
</div>-->

<!--<div class="homepage-gallery">
        <div class="main-title-1">
                <span>Latest photos</span>
                <a href="#">check our flickr page</a>
        </div>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
        <a href="#"><img src="images/image-overlay-75x75.png" alt="" width="75" height="80" style="background: url(images/photos/no-image-75x75.jpg) 0 0 no-repeat;" /></a>
</div>-->


