Cufon.replace('h2, h3, h4, h5, h6', { fontFamily: 'Prima', hover: 'true' } );
Cufon.replace('.main-menu table tr td > ul > li', { fontFamily: 'Prima', hover: true, hoverables: { li: true }, ignore: { ul: true } } );
Cufon.replace('.homepage-slider .navigation .intro a', { fontFamily: 'Prima', hover: 'true', textShadow: '#850402 0 1px 0' } );
Cufon.replace('.blog-slider .navigation .intro a', { fontFamily: 'Prima', hover: 'true', textShadow: '#850402 0 1px 0' } );
Cufon.replace('.main-logo .title', { fontFamily: 'Art Post', hover: 'true', textShadow: '#494949 0 1px 0' } );
Cufon.replace('.homepage-columns-item .title', { fontFamily: 'Prima', textShadow: '#000 0 1px 0', hover: 'true' } );
Cufon.replace('.more-link', { fontFamily: 'Prima', textShadow: '#000 0 1px 0', hover: 'true' } );
Cufon.replace('.latest-blog .item .title a', { fontFamily: 'Prima', textShadow: '#000 0 1px 0', hover: 'true' } );
Cufon.replace('.main-title-1', { fontFamily: 'Prima', textShadow: '#000 0 1px 0', hover: 'true' } );
Cufon.replace('.main-title-2', { fontFamily: 'Prima', textShadow: '#000 0 1px 0', hover: 'true' } );
Cufon.replace('.pages-1 .default', { fontFamily: 'Prima', textShadow: '#fff 0 1px 0', hover: 'true' } );
Cufon.replace('.pages-1 .active', { fontFamily: 'Prima', textShadow: '#000 0 1px 0', hover: 'true' } );
Cufon.replace('.comments-item .user', { fontFamily: 'Prima', hover: 'true' } );
Cufon.replace('.comments-item .reply', { fontFamily: 'Prima', hover: 'true' } );
Cufon.replace('.btn-1', { fontFamily: 'Prima', textShadow: '#fff 0 1px 0', hover: 'true' } );
Cufon.replace('.btn-2', { fontFamily: 'Prima', textShadow: '#1b1b1b 0 1px 0', hover: 'true' } );
Cufon.replace('.photo-gallery-list .photo-gallery-subtitle span', { fontFamily: 'Prima' } );
Cufon.replace('.success p', { fontFamily: 'Prima' } );
Cufon.replace('.no-comments p', { fontFamily: 'Prima' } );
Cufon.replace('.switcher p', { fontFamily: 'Prima' } );